name: ci

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: configure gpg key
        run: |
          echo -n "$GPG_PUBLIC_KEY" | base64 --decode | gpg --import
        env:
          GPG_PUBLIC_KEY: ${{secrets.GPG_PUBLIC_KEY}}

      - name: build
        run: mvn -B clean verify

      - name: generate badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: 'tests-parent/coverage-report/target/site/jacoco-aggregate/jacoco.csv'

      - name: commit badge
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'claypigeon123'
            git config --global user.email 'claypigeon123@users.noreply.github.com'
            git add -A
            git commit -m "autogenerated coverage badge"
            git push
          fi